services:
  - type: web
    name: compressapp-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
